### ISSUE TITLE
Implementation Dashboard - Going Public

### ISSUE THREAD

**Issue by laurentsenta** [ipfs/gateway-conformance#169]
Contributes to https://github.com/ipfs/gateway-conformance/issues/123
See comment in https://github.com/ipfs/gateway-conformance/pull/152#issuecomment-1705531259

### Get our domain name | 1 day

- [x] Decide and deploy to our production's domain name

### Update documentation  | 1 day

- [x] Document how to add a new implementation to the dashboard
- [x] Document the generation flow
- [x] Link to the dashboard from this repo's README

### surface job URL better and render details | 1 day

- [x] what commit of the conformance test suite we ran
- [x] what commit of the implementation we ran against
- [x] date when these results are from

### Link to this dashboard | 1 day

- [ ] Link to this dashboard from specs - we should be able to link specs to a precise page
- [ ] Link to this dashboard from IPFS Docs

### Make future development simpler | 1 day

- [x] Add a temporary preview deploy URL in PR to test the dashboard (with a triggered job?)

**Comment by laurentsenta** [comment]
@lidel @BigLep who should be involved with deciding on the domain name for the dashboard?

We talked about using gateway conformance to test other ipfs specs, like unixfs, etc. So I would propose https://conformance.ipfs.tech

**Comment by lidel** [comment]
`conformance.ipfs.tech` `conformance.ipfs.tech` sgtm.

@laurentsenta  @BigLep  Just an idea, but since we want to leverage this for testing things beyond gateway semantics, 
thoughts on short and straight to the point `test.ipfs.tech`? I'm ok wither way.

ps. before going live, we need to improve the [landing page](https://ipfs.github.io/gateway-conformance/), make it more informative, and link to other test suites that exist (so it acts as one-time-stop for discovering conformance test suites beyond gateway-conformance too).

**Comment by BigLep** [comment]
I like the idea of being able to go to a landing page to learn about "IPFS testing".  That said, that is a broader topic as ideally cover (implementation) unit testing, (implementation) integration testing, (multiple implementation) conformance testing.  It would seem a bit odd for https://github.com/ipfs/gateway-conformance to be the place pointing to implementation testing topics.  As a result, maybe `conformance.ipfs.tech` to be clear about the slice of testing we're focused on here?   (Separately and out of scope here there could be a docs.ipfs.tech page that discusses how testing is done in IPFS, which is just links to implementation pages and conformance.ipfs.tech)?

I'm good with what you decide here.  I just want to make sure we don't name squat on a broad topic like "testing" if that isn't something we plan to fully cover here.

Agreed though that expanding the landing page is good/right to do covering things like:
- Why
- How
- Related Projects

**Comment by BigLep** [comment]
@laurentsenta : just checking in on the status here.  Do we have an estimate on when this will land?

**Comment by laurentsenta** [comment]
@BigLep thanks for the status check; I'd like to get the dashboard released this week so we can review the copy next week.

infra PR: is in https://github.com/protocol/infra/pull/1299
fleek deploy PR: https://github.com/ipfs/gateway-conformance/pull/177

fwiw, thanks to @lidel feedback, we aligned with the specs, it looks like this now:

<img width="868" alt="CleanShot 2023-11-07 at 13 34 06@2x" src="https://github.com/ipfs/gateway-conformance/assets/1136669/f80e9a52-d97b-4903-b0ca-a9c835afe8e9">

**Comment by lidel** [comment]
Had sync with @laurentsenta  today, and I believe we got everything we needed from IPDX for MVP before nucleations. Marking this as closed, thank you!

If there are missing features, we will triage and plan after IPDX nucleation activities are done

Remaining work is in Stewards size of court, tracked in https://github.com/ipfs/specs/issues/456
