### ISSUE TITLE
bug: gateway-conformance subdomains are inflexible and setup is not clear

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/gateway-conformance#185]
I'm trying to improve on conformance of [helia-http-gateway](https://github.com/ipfs/helia-http-gateway/pull/57), and I am continuously getting failures from the gateway-conformance tool (via docker and directly with `go run ./cmd/gateway-conformance/main.go test # ...`) 

I believe these may be related to whatever proxying thing is happening under the hood, because i've seen this error more than a few times:

```
Error: Querying http://localhost/ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am/ failed: Get "http://localhost/ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am/": proxyconnect tcp: dial tcp [::1]:8090: connect: connection refused
```

Some questions:

1. If I am specifying `--gateway-url 'http://localhost:8090' --subdomain-url 'http://localhost:8090'`, why is the gateway-conformance tool querying `localhost` with no port?
2. Why are dials going to an ip6 address (that is not supported on my machine) and can I disable that?
3. Can we disable the proxy entirely? is there a way to run tests directly against a gateway and verify the actual HTTP headers and responses?

**Comment by SgtPooki** [comment]
I also get the following error quite frequently:

```
Error: Querying http://localhost/ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am/ failed: Get "http://localhost/ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am/": proxyconnect tcp: unexpected EOF
```

but this is very odd because the request works perfectly fine in a browser:

![image](https://github.com/ipfs/gateway-conformance/assets/1173416/b05372d8-10b0-46af-9f24-8c63af147d42)

**Comment by SgtPooki** [comment]
Running the test command with ENV vars instead seems to work...?

```
SUBDOMAIN_GATEWAY_URL="http://localhost:8090" GATEWAY_URL="http://localhost:8090" go run ./cmd/gateway-conformance/main.go test --json gwc-report.json --verbose -- -timeout 30m -run 'TestGatewaySubdomains/request_for_example.com%2Fipfs%2F%7BCIDv1%7D_redirects_to_subdomain_%28HTTP_proxy_tunneling_via_CONNECT%29#01'
```

**Comment by SgtPooki** [comment]
> Running the test command with ENV vars instead seems to work...?
> 
> ```
> SUBDOMAIN_GATEWAY_URL="http://localhost:8090" GATEWAY_URL="http://localhost:8090" go run ./cmd/gateway-conformance/main.go test --json gwc-report.json --verbose -- -timeout 30m -run 'TestGatewaySubdomains/request_for_example.com%2Fipfs%2F%7BCIDv1%7D_redirects_to_subdomain_%28HTTP_proxy_tunneling_via_CONNECT%29#01'
> ```


but not when run via docker with 

```
docker run --network host -v $PWD:/workspace -w /workspace --env SUBDOMAIN_GATEWAY_URL='http://localhost:8090' --env GATEWAY_URL='http://localhost:8090' ghcr.io/ipfs/gateway-conformance:v0.4.2 test --verbose --json gwc-report.json --specs subdomain-ipns-gateway,subdomain-ipfs-gateway -- -timeout 30m -run TestGatewaySubdomains/request_for_example.com%2Fipfs%2F%7BCIDv1%7D_redirects_to_subdomain_%28HTTP_proxy_tunneling_via_CONNECT%29#01
```

**Comment by laurentsenta** [comment]
> 1. if I am specifying --gateway-url 'http://localhost:8090' --subdomain-url 'http://localhost:8090', why is the gateway-conformance tool querying localhost with no port?

Looks like a bug, we haven't tested gateways behind subdomains with ports. We'd need to update the subdomain tests to keep the port as well (cc @lidel).

[Example of a test that loses the port](https://github.com/ipfs/gateway-conformance/blob/d855ec4fb9dac4a5aaecf3776037b005cc74c566/tests/subdomain_gateway_ipns_test.go#L56C4-L56C4). The localhost tests might require a light refactor to force the port somehow ([code](https://github.com/ipfs/gateway-conformance/blob/d855ec4fb9dac4a5aaecf3776037b005cc74c566/tooling/test/config.go#L32))

> 2. Why are dials going to an ip6 address (that is not supported on my machine) and can I disable that?

The `gateway-url` is the address the test suite connects to. In your case, the test suite always connects to `localhost:8090`. I'm surprised the test suite or golang would mess with the hostname mapping.

Could you double-check your `/etc/hosts` for a mapping `::1 localhost`?

> 3. Can we disable the proxy entirely? is there a way to run tests directly against a gateway and verify the actual HTTP headers and responses?

So the `subdomain-url` is exclusively used to test the [subdomain specs](https://specs.ipfs.tech/http-gateways/subdomain-gateway/). But the test suite ONLY connects to the gateway-url (localhost:8090). The subdomain is "simulated". More details in the [docs](https://github.com/ipfs/gateway-conformance/blob/main/docs/commands.md#subdomain-testing-and-subdomain-url).

What do you mean by disabling the proxy entirely? My recommendation would be to NOT test the subdomain specs, maybe get started with the simpler ones.

For example, use `--specs -subdomain-gateway,-dnslink-gateway` to test everything but DNS Link and subdomains (they are tricky to setup). Or use `--specs trustless-gateway` to start from the trustless specs (should be straightforward).

More examples in the [docs](https://github.com/ipfs/gateway-conformance/blob/main/docs/examples.md)

**Comment by SgtPooki** [comment]
> Could you double-check your `/etc/hosts` for a mapping `::1 localhost`?
> 
> >

good call: 

`::1             localhost`

and thanks for the rest of the links, super helpful. figuring out how to filter out tests right now is a lot of the trouble, but running tests from vscode is making determining those much easier

**Comment by lidel** [comment]
I see how having two URLs options here becomes confusing:

> ```--gateway-url 'http://localhost:8090' --subdomain-url 'http://localhost:8090'```

Perhaps an useful insight is that subdomain gateway is not related to URL at all.
It is a feature that looks at `Host` HTTP header from the request, nothing more.
If there is no `Host`, then even if request was sent to `localhost:8080`, it won't be processed as a subdomain request.

I took a stab at improving docs in https://github.com/ipfs/gateway-conformance/pull/193

Here, it should be something like: ```--gateway-url 'http://127.0.0.0.1:8090' --subdomain-url 'http://example.com'``` just to avoid confusion with localhost.

@SgtPooki try following prior art used for testing kubo, such as

https://github.com/ipfs/gateway-conformance/blob/4760ba747731910c0b7b702a6d089fd3e932ab74/.github/workflows/test-kubo-e2e.yml#L65-L66

With this, all you need to do is to make sure your gateway implementation has subdomain gateway enabled on `example.com` (and/or `localhost`) hostnames [like we do in kubo](https://github.com/ipfs/kubo/blob/8c4bdd8556e0c8b1a4ea3a6d703402bd6cfe1229/.github/workflows/gateway-conformance.yml#L24-L32) – this way you don't need to pass `--subdomain-url 'http://example.com'` at all.

And I agree with @laurentsenta, will be easier to disable `subdomain-gateway` until you pass regular `path-gateway` first.

### Digression on why we see "localhost without port in tests"

Gateway feature could be enabled per origin (DNS name+port+protocol), but in real world it is easier to implement and reason about enabling this feature globally per DNS name.

For example, in Kubo, subdomain gateway is implicitly enabled on `localhost` DNS name, without a port.

This is also why we have tests that seem to ignore port in the `Host` header, but things still work.

Yes, this could be fixed, but it also is cosmetic, and only impacts `localhost` case (production URLs use implicit port, not present in base URL)

**Comment by SgtPooki** [comment]
@lidel lack of port support is making gateway-conformance support in verified-fetch a pita. 

"real world" usecase is developers testing their servers in CI, which will likely not be on implicit ports.

**Comment by lidel** [comment]
@SgtPooki let's reopen and discuss it here instead of slack. 

It has been a while, could you describe what exactly gets painful in your setup what would be the preferred fix? 

I looked at https://github.com/ipfs/helia-verified-fetch/pull/85/files#diff-175730b97b315afceee1b708f9bd876588ef883662dc52e139a7961ac7804c56R100 
and would being able to pass `--gateway-url 'http://127.0.0.0.1:8090' --subdomain-url 'http://example.com:8090'`, and have conformance tests respecting the passed port in their asserts origins?  Or did I miss the point?

**Comment by SgtPooki** [comment]
> have conformance tests respecting the passed port in their Host header asserts origins? Or did I miss the point?

this would fix my concerns for sure. and remove the need for the header munging with `fixingGwcAnnoyance`

**Comment by SgtPooki** [comment]
diving in a bit more, `u` = https://pkg.go.dev/net/url#URL, which has `.Host` key that should contain the port number.. why doesn't it?

**Comment by SgtPooki** [comment]
it seems like this is the problem:

1. hardcoded `localhost`: https://github.com/ipfs/gateway-conformance/blob/c0dafe17ad01f112530ab788caef4a58483847ab/tooling/test/config.go#L32
2. consumed by https://github.com/ipfs/gateway-conformance/blob/c0dafe17ad01f112530ab788caef4a58483847ab/tests/subdomain_gateway_ipfs_test.go#L22-L26

This seems like an implicit dependence on kubo's "accept all things on localhost" requirement, which will break in any gateway testing where that's not true/possible.

**Comment by lidel** [comment]
Thanks for digging into this. I think we should fix the conformance tests to run test against explicit port.  Your pointers are very useful, I'll see if I can open a PR later today/tomorrow.

**Comment by lidel** [comment]
Spent some time spelunking and thinking how to clean this up.

Just like you noted, the underlying problem is not really Kubo specific, but the way gateway-conformance has hardcoded subdomain tests to always run against both `SUBDOMAIN_GATEWAY_URL` and `localhost`.

It was likely a quick&dirty way to ensure we keep testing localhost ipfs-desktop/companion and brave use cases, but now it should be explicit rather implicit.

--- 

I have local PR that cleans this up, but I've noticed additional problems, so will take a bit longer than expected to finish all loose ends. For now I will be tracking progress here, and open PR once ready. We will likely have to release it as `v6`, due to breaking changes.

### Cleanup progress


- [x] only test against what is explicitly passed via `--subdomain-url`, remove implicit (hardcoded) tests against localhost
- [x] allow `--subdomain-url` to be a comma-separated list, so we can keep localhost tests in Kubo by having ``--subdomain-url http://example.com,http://localhost:port`
- [ ] make `--subdomain-url`  optional, and disabled by default, but required if `--specs +subdomain-gateway` is passed
- [ ] decouple `tests/dnslink_gateway_test.go` from `--subdomain-url`, this is invalid, we should be testing against to be added `--dnslink-url`
- [ ] PR in Kubo that updates CI with explicit flags, make sure it passes
- [ ] release `gateway-conformance@v6` with cleanup
- [ ] switch Kubo
- [ ] switch Rainbow
- [ ] switch Boxo
