### ISSUE TITLE
Trustless Gateway: "GET CAR with entity-bytes requesting a range from the end of a file" test expects in correct behavior

### ISSUE THREAD

**Issue by hannahhoward** [ipfs/gateway-conformance#189]
# What

[This test](https://github.com/ipfs/gateway-conformance/blob/main/tests/trustless_gateway_car_test.go#L620) reads a file with an entity-bytes param from the -99999 index (i.e. beginning of the file) up to the -3 index (i.e. everything but the last two bytes). 

The expectations as written appear to be testing that all but the last block of the generated car file are returned:
https://github.com/ipfs/gateway-conformance/blob/main/tests/trustless_gateway_car_test.go#L637

However, if one looks at the underlying file, https://github.com/ipfs/gateway-conformance/blob/main/fixtures/trustless_gateway_car/subdir-with-mixed-block-files.car, via CAR inspection, one funds the underlying file is 4098 bytes long, with each block 1024 bytes, for 4 1024 blocks and 1 2 byte block to complete the file. So it has a total of 5 blocks.

Meaning that https://github.com/ipfs/gateway-conformance/blob/main/tests/trustless_gateway_car_test.go#L637 as written is actually expecting the whole file to be read, which is incorrect behavior.

The reason it passes for boxo is due to a seperate bug -- https://github.com/ipfs/boxo/pull/523

**Comment by lidel** [comment]
Thank you for reporting and taking time to provide PRs with fixes @hannahhoward.

Will bring this up during triage and will prioritize reviews
(realistically, after tasks related to https://github.com/ipfs/kubo/issues/10045 are wrapped up, but before EOW)
