### ISSUE TITLE
Add dedicated compliance targets for Trustless Gateway 

### ISSUE THREAD

**Issue by lidel** [ipfs/gateway-conformance#74]
Discussed this briefly with @laurentsenta, projects like Saturn, Rhea, Boost etc will benefit from a test targets that only check compliance with https://specs.ipfs.tech/http-gateways/trustless-gateway/ spec.

We already have some prior art for [Subdomain Gateways and IPNS](https://github.com/ipfs/gateway-conformance/blob/81be5d516eba416c28586a2b33c3fda776cba704/tooling/specs/specs.go#L30-L32).

Ideally, we would provide targets for requested subsets of the spec (we know some use cases won't care about IPNS or CARs).

My thinking is to add:
1. `trustless-block-gateway` Just Blocks (no paths) – bare minimum, the most basic type of trustless gateway
2. `trustless-block-car-gateway`  Blocks and CARs with paths (@aarshkshah1992 would like to run this in Rhea projects)
3. `trustless-block-car-ipns-gateway` Blocks, CARs, and IPNS Records, enabling end-to-end verifiability of both `/ipfs` and `/ipns`. (we would run this in Kubo and bifrost-gateway)

cc @hacdias  – up to you if we add this to https://github.com/ipfs/gateway-conformance/pull/56 or do a follow-up PR

**Comment by hacdias** [comment]
I think we should do this **after** #56.
