### ISSUE TITLE
Version 0.2

### ISSUE THREAD

**Issue by laurentsenta** [ipfs/gateway-conformance#80]
- [ ] Upgrade kubo and boxo to load domains AND subdomains DNSLinks (see [PR](https://github.com/ipfs/gateway-conformance/pull/53/files#diff-41f34cd4fcf57bd8b77f08880e94fe08ae40bf31084f70717d621372d9ddbc45))
- [ ] Upgrade kubo and boxo to use `dag import .... --pin-roots=false` (See [PR](https://github.com/ipfs/gateway-conformance/pull/85))

**Comment by lidel** [comment]
@laurentsenta  after you ship 0.2, drop a note for  Saturn folks in  https://github.com/filecoin-saturn/L1-node/issues/447 – they want to dogfood this asap (only the trustless block and car, without IPNS)
